name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: version
      run: |
        echo -n "version=" >> "$GITHUB_OUTPUT"
        git describe >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go run build.go -version "${{steps.version.outputs.version}}"

    - name: Test
      run: go test -v -short ./...
